export interface action {
    type: any
    payload: any
}
export const userType = {
    SET_TOKEN: 'SET_TOKEN',
    SET_SELF_DATA: 'SET_SELF_DATA',
    CLEAR_TOKEN: 'CLEAR_TOKEN',
    CLEAR_USER_ALL: 'CLEAR_USER_ALL'
}
export const companyType = {
    SET_BANCH: 'SET_BANCH',
    SET_EMPLOYEE: 'SET_EMPLOYEE',
    SET_BANCH_STYLE: ' SET_BANCH_STYLE',
    SET_BANCH_RULE: 'SET_BANCH_RULE',
    SET_COMPANY: 'SET_COMPANY',
    SET_WEEKEND_SETTING: 'SET_WEEKEND_SETTING',
    SET_WAIT_REPLY: 'SET_WAIT_REPLY',
    CLEAR_COMPANY_ALL: 'CLEAR_COMPANY_ALL'
}

export const statusType = {
    ENTRY_ON: 'ENTRY_ON',
    ENTRY_OFF: 'ENTRY_OFF',

    FETCH_COMPANY_ON: 'FETCH_COMPANY_ON',
    FETCH_COMPANY_OFF: 'FETCH_COMPANY_OFF',

    UPDATE_COMPANY_ON: 'UPDATE_COMPANY_ON',
    UPDATE_COMPANY_OFF: 'UPDATE_COMPANY_OFF',

    FETCH_BANCH_ON: 'FETCH_BANCH_ON',
    FETCH_BANCH_OFF: 'FETCH_BANCH_OFF',
    UPDATE_BANCH_ON: 'UPDATE_BANCH_ON',
    UPDATE_BANCH_OFF: 'UPDATE_BANCH_OFF',
    CREATE_BANCH_ON: 'CREATE_BANCH_ON',
    CREATE_BANCH_OFF: 'CREATE_BANCH_OFF',

    FETCH_USER_ALL_ON: 'FETCH_USER_ALL_ON',
    FETCH_USER_ALL_OFF: 'FETCH_USER_ALL_OFF',
    UPDATE_USER_ON: 'UPDATE_USER_ON',
    UPDATE_USER_OFF: 'UPDATE_USER_OFF',

    FETCH_SELF_DATA_ON: 'FETCH_SELF_INFO_ON',
    FETCH_SELF_DATA_OFF: 'FETCH_SELF_INFO_OFF',
    UPDATE_SELF_DATA_ON: 'UPDATE_SELF_DATA_ON',
    UPDATE_SELF_DATA_OFF: 'UPDATE_SELF_DATA_OFF',

    FETCH_BANCH_STYLE_ON: 'FETCH_BANCH_STYLE_ON',
    FETCH_BANCH_STYLE_OFF: 'FETCH_BANCH_STYLE_OFF',
    UPDATE_BANCH_STYLE_ON: 'UPDATE_BANCH_STYLE_ON',
    UPDATE_BANCH_STYLE_OFF: 'UPDATE_BANCH_STYLE_OFF',
    CREATE_BANCH_STYLE_ON: 'CREATE_BANCH_STYLE_ON',
    CREATE_BANCH_STYLE_OFF: 'CREATE_BANCH_STYLE_OFF',
    DELETE_BANCH_STYLE_ON: 'DELETE_BANCH_STYLE_ON',
    DELETE_BANCH_STYLE_OFF: 'DELETE_BANCH_STYLE_OFF',

    FETCH_BANCH_RULE_ON: 'FETCH_BANCH_RULE_ON',
    FETCH_BANCH_RULE_OFF: 'FETCH_BANCH_RULE_OFF',
    UPDATE_BANCH_RULE_ON: 'UPDATE_BANCH_RULE_ON',
    UPDATE_BANCH_RULE_OFF: 'UPDATE_BANCH_RULE_OFF',
    CREATE_BANCH_RULE_ON: 'CREATE_BANCH_RULE_ON',
    CREATE_BANCH_RULE_OFF: 'CREATE_BANCH_RULE_OFF',
    DELETE_BANCH_RULE_ON: 'DELETE_BANCH_RULE_ON',
    DELETE_BANCH_RULE_OFF: 'DELETE_BANCH_RULE_OFF',

    FETCH_WEEKEND_SETTING_ON: 'FETCH_WEEKEND_SETTING_ON',
    FETCH_WEEKEND_SETTING_OFF: 'FETCH_WEEKEND_SETTING_OFF',
    CREATE_WEEKEND_SETTING_ON: 'CREATE_WEEKEND_SETTING_ON',
    CREATE_WEEKEND_SETTING_OFF: 'CREATE_WEEKEND_SETTING_OFF',
    DELETE_WEEKEND_SETTING_ON: 'DELETE_WEEKEND_SETTING_ON',
    DELETE_WEEKEND_SETTING_OFF: 'DELETE_WEEKEND_SETTING_OFF',

    FETCH_WAIT_REPLY_ON: 'FETCH_WAIT_REPLY_ON',
    FETCH_WAIT_REPLY_OFF: 'FETCH_WAIT_REPLY_OFF',
    CREATE_WAIT_REPLY_ON: 'CREATE_WAIT_REPLY_ON',
    CREATE_WAIT_REPLY_OFF: 'CREATE_WAIT_REPLY_OFF',
    UPDATE_WAIT_REPLY_ON: 'UPDATE_WAIT_REPLY_ON',
    UPDATE_WAIT_REPLY_OFF: 'UPDATE_WAIT_REPLY_OFF',

    CLEAR_STATUS_ALL: 'CLEAR_STATUS_ALL'
}

export const shiftEditType = {
    SET_SHIFT_ONLINE_USER: 'SET_SHIFT_ONLINE_USER',
    SET_SHIFT_STATUS: 'SET_SHIFT_STATUS',
    CLEAR_SHIFT_ALL: 'CLEAR_SHIFT_ALL'
}
