FROM nginx:1.22
# RUN cat certificate.crt ca_bundle.crt >> certificate.crt
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./certificate.crt /etc/ssl/certificate.crt
COPY ./private.key /etc/ssl/private.key