FROM nginx:1.22
# RUN cat certificate.crt ca_bundle.crt >> certificate.crt
# RUN apt-get update -y
# RUN apt-get install certbot python3-certbot-nginx -y
# RUN nginx -t
# RUN certbot certonly --nginx --http-01-port 443 --email za96346@gmail.com --agree-tos -d workhard.app
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
# COPY ./certificate.crt /etc/ssl/certificate.crt
# COPY ./private.key /etc/ssl/private.key